#! /usr/bin/env python

# vim: set expandtab ts=4 sw=4 filetype=python:

"""
Print every entity associated with the project.
"""

import optparse
from pitz.project import Project
from pitz.cmdline import *

p = setup_options()

options, args = p.parse_args()

path_to_yaml_file = options.pitz_dir or Project.find_yaml_file()

proj = Project.from_yaml_file(path_to_yaml_file)

d = build_filter(args)

results = proj

if d:
    results = results(**d)

if options.grep:
    results = results.grep(options.grep)

send_through_pager(str(results))
