#! /usr/bin/env python

# vim: set expandtab ts=4 sw=4 filetype=python:

"""
Print the todo list.
"""

import optparse, os, sys
from pitz.project import Project
from pitz.cmdline import setup_options, build_filter

p = setup_options()

options, args = p.parse_args()

path_to_yaml_file = options.pitz_dir or Project.find_yaml_file()

proj = Project.from_yaml_file(path_to_yaml_file)

d = build_filter(args)

if d:
    results = proj.todo(**d)
else:
   results = proj.todo

if options.summarized_view:
    print(results.summarized_view)

else:
    print(results)
