#! /usr/bin/env python

# vim: set expandtab ts=4 sw=4 filetype=python:

"""
Start IPython and load up your project.
"""

import optparse, os, sys

p = optparse.OptionParser()

def verify_projectfile(option, opt_str, value, parser):

    if not os.path.isfile(value):
        raise optparse.OptionValueError("%s is not a file!" % value)

    else:
        parser.values.projectfile = value

p.set_usage('%prog [path to project file]')

options, args = p.parse_args()

from pitz.cmdline import shell

shell(*args)
