#! /usr/bin/env python

# vim: set expandtab ts=4 sw=4 filetype=python:

import optparse, os, sys

p = optparse.OptionParser()

def verify_projectfile(option, opt_str, value, parser):

    if not os.path.isfile(value):
        raise optparse.OptionValueError("%s is not a file!" % value)

    else:
        parser.values.projectfile = value
        

p.add_option('--project-file',
    help='path to project yaml file',
    action="callback",
    callback=verify_projectfile,
    dest="projectfile",
    type="string")

options, args = p.parse_args()

if not options.projectfile:
    p.print_help()
    sys.exit(1)

from pitz.cmdline import shell

shell(options.projectfile)
