#! /usr/bin/env python

# vim: set expandtab ts=4 sw=4 filetype=python:

"""
Print the detailed view for a UUID given at the command line.
"""


import optparse, os, sys
from pitz.project import Project
from pitz.cmdline import *
from pitz.entity import Entity

p = setup_options()

options, args = p.parse_args()

if not args:
    p.print_usage()
    sys.exit()

path_to_yaml_file = options.pitz_dir or Project.find_yaml_file()

proj = Project.from_yaml_file(path_to_yaml_file)

e = proj[args[0]]

if isinstance(e, Entity):
    send_through_pager(e.detailed_view)

else:
    print("Sorry, couldn't find %s" % args[1])
