#! /usr/bin/env python

# vim: set expandtab ts=4 sw=4 filetype=python:

"""
Print the detailed view for a UUID given at the command line.
"""

import optparse, os, sys

from pitz.project import Project
from pitz.entity import Entity

p = optparse.OptionParser()

p.set_usage('%prog [path to project file] [UUID]')

options, args = p.parse_args()

path_to_yaml_file = args[0] if args else Project.find_yaml_file()
proj = Project.from_yaml_file(path_to_yaml_file)

e = proj[args[1]]

if isinstance(e, Entity):
    print(e.detailed_view)

else:
    print("Sorry, couldn't find %s" % args[1])
